// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuco66iMWgILsKbW8nYVU2Mjpw3nY7XY',
    appId: '1:753660236604:web:d50c029f3e218990510439',
    messagingSenderId: '753660236604',
    projectId: 'udemy-flutter-todo-app',
    authDomain: 'udemy-flutter-todo-app.firebaseapp.com',
    storageBucket: 'udemy-flutter-todo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8DX2vOKdn77MVFmTztbgGTdqqXgE73g',
    appId: '1:753660236604:android:50f324ee653cc876510439',
    messagingSenderId: '753660236604',
    projectId: 'udemy-flutter-todo-app',
    storageBucket: 'udemy-flutter-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfKj0NcrOGnmlC7-BHuxM_v3yub_ulssU',
    appId: '1:753660236604:ios:3bdfc0c23fa561e3510439',
    messagingSenderId: '753660236604',
    projectId: 'udemy-flutter-todo-app',
    storageBucket: 'udemy-flutter-todo-app.appspot.com',
    iosClientId: '753660236604-8o41hgfp82387s8g8snrmkd1hq0v3ogg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfKj0NcrOGnmlC7-BHuxM_v3yub_ulssU',
    appId: '1:753660236604:ios:3bdfc0c23fa561e3510439',
    messagingSenderId: '753660236604',
    projectId: 'udemy-flutter-todo-app',
    storageBucket: 'udemy-flutter-todo-app.appspot.com',
    iosClientId: '753660236604-8o41hgfp82387s8g8snrmkd1hq0v3ogg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseTodoApp',
  );
}
