// Mocks generated by Mockito 5.2.0 from annotations
// in advisor_app/test/infrastructure/repositories/theme_repository_impl.test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:advisor_app/infrastructure/datasources/theme_local_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ThemeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeLocalDataSource extends _i1.Mock
    implements _i2.ThemeLocalDataSource {
  MockThemeLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> setDarkModeLocally(bool? value) =>
      (super.noSuchMethod(Invocation.method(#setDarkModeLocally, [value]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<bool> getIsDarkModeLocally() =>
      (super.noSuchMethod(Invocation.method(#getIsDarkModeLocally, []),
          returnValue: Future<bool>.value(false)) as _i3.Future<bool>);
}
